// DO NOT EDIT
// Auto-generated
// Copyright (C) 2012 Potix Corporation. All Rights Reserved.
part of rikulo_view;

class _StyleImpl implements CssStyleDeclaration {
  final View _view;
  _StyleImpl(View this._view);

  CssStyleDeclaration get _st => _view.node.style;

  //@override
  String getPropertyValue(String propertyName)
  => _st.getPropertyValue(propertyName);
  //@override
  String removeProperty(String propertyName)
  => _st.removeProperty(propertyName);
  //@override
  CssValue getPropertyCssValue(String propertyName)
  => _st.getPropertyCssValue(propertyName);
  //@override
  String getPropertyPriority(String propertyName)
  => _st.getPropertyPriority(propertyName);
  //@override
  String getPropertyShorthand(String propertyName)
  => _st.getPropertyShorthand(propertyName); 
  //@override
  bool isPropertyImplicit(String propertyName)
  => _st.isPropertyImplicit(propertyName);

  //@override
  void setProperty(String propertyName, String value, [String priority]) {
    if (?priority)
      _st.setProperty(propertyName, value, priority);
    else
      _st.setProperty(propertyName, value);
  }

  //@override
  String get cssText => _st.cssText;
  //@override
  void set cssText(String value) {
    final st = _st;
    st.cssText = value;

    var v;
    if ((v = st.left).isEmpty) //restore if not set
      st.left = Css.px(_view.left);
    else
      _view.left = Css.intOf(v);

    if ((v = st.top).isEmpty)
      st.top = Css.px(_view.top);
    else
      _view.top = Css.intOf(v);

    if ((v = st.width).isEmpty)
      st.width = Css.px(_view.width);
    else
      _view.width = Css.intOf(v, defaultValue: null);

    if ((v = st.height).isEmpty)
      st.height = Css.px(_view.height);
    else
      _view.height = Css.intOf(v, defaultValue: null);
  }

  //@override
  int get length => _st.length;
  //@override
  String item(int index) => _st.item(index);
  //@override
  CssRule get parentRule => _st.parentRule;

  String get left => _st.left;
  void set left(String v) {_view.left = Css.intOf(v);}
  String get top => _st.top;
  void set top(String v) {_view.top = Css.intOf(v);}

  String get width => _st.width;
  void set width(String v) {
    _view.width = Css.intOf(v, defaultValue: null);
  }
  String get height => _st.height;
  void set height(String v) {
    _view.height = Css.intOf(v, defaultValue: null);
  }

  String get alignContent => _st.alignContent;
  void set alignContent(String v) {_st.alignContent = _s(v);}
  String get alignItems => _st.alignItems;
  void set alignItems(String v) {_st.alignItems = _s(v);}
  String get alignSelf => _st.alignSelf;
  void set alignSelf(String v) {_st.alignSelf = _s(v);}
  String get animation => _st.animation;
  void set animation(String v) {_st.animation = _s(v);}
  String get animationDelay => _st.animationDelay;
  void set animationDelay(String v) {_st.animationDelay = _s(v);}
  String get animationDirection => _st.animationDirection;
  void set animationDirection(String v) {_st.animationDirection = _s(v);}
  String get animationDuration => _st.animationDuration;
  void set animationDuration(String v) {_st.animationDuration = _s(v);}
  String get animationFillMode => _st.animationFillMode;
  void set animationFillMode(String v) {_st.animationFillMode = _s(v);}
  String get animationIterationCount => _st.animationIterationCount;
  void set animationIterationCount(String v) {_st.animationIterationCount = _s(v);}
  String get animationName => _st.animationName;
  void set animationName(String v) {_st.animationName = _s(v);}
  String get animationPlayState => _st.animationPlayState;
  void set animationPlayState(String v) {_st.animationPlayState = _s(v);}
  String get animationTimingFunction => _st.animationTimingFunction;
  void set animationTimingFunction(String v) {_st.animationTimingFunction = _s(v);}
  String get appearance => _st.appearance;
  void set appearance(String v) {_st.appearance = _s(v);}
  String get appRegion => _st.appRegion;
  void set appRegion(String v) {_st.appRegion = _s(v);}
  String get aspectRatio => _st.aspectRatio;
  void set aspectRatio(String v) {_st.aspectRatio = _s(v);}
  String get backfaceVisibility => _st.backfaceVisibility;
  void set backfaceVisibility(String v) {_st.backfaceVisibility = _s(v);}
  String get background => _st.background;
  void set background(String v) {_st.background = _s(v);}
  String get backgroundAttachment => _st.backgroundAttachment;
  void set backgroundAttachment(String v) {_st.backgroundAttachment = _s(v);}
  String get backgroundClip => _st.backgroundClip;
  void set backgroundClip(String v) {_st.backgroundClip = _s(v);}
  String get backgroundColor => _st.backgroundColor;
  void set backgroundColor(String v) {_st.backgroundColor = _s(v);}
  String get backgroundComposite => _st.backgroundComposite;
  void set backgroundComposite(String v) {_st.backgroundComposite = _s(v);}
  String get backgroundImage => _st.backgroundImage;
  void set backgroundImage(String v) {_st.backgroundImage = _s(v);}
  String get backgroundOrigin => _st.backgroundOrigin;
  void set backgroundOrigin(String v) {_st.backgroundOrigin = _s(v);}
  String get backgroundPosition => _st.backgroundPosition;
  void set backgroundPosition(String v) {_st.backgroundPosition = _s(v);}
  String get backgroundPositionX => _st.backgroundPositionX;
  void set backgroundPositionX(String v) {_st.backgroundPositionX = _s(v);}
  String get backgroundPositionY => _st.backgroundPositionY;
  void set backgroundPositionY(String v) {_st.backgroundPositionY = _s(v);}
  String get backgroundRepeat => _st.backgroundRepeat;
  void set backgroundRepeat(String v) {_st.backgroundRepeat = _s(v);}
  String get backgroundRepeatX => _st.backgroundRepeatX;
  void set backgroundRepeatX(String v) {_st.backgroundRepeatX = _s(v);}
  String get backgroundRepeatY => _st.backgroundRepeatY;
  void set backgroundRepeatY(String v) {_st.backgroundRepeatY = _s(v);}
  String get backgroundSize => _st.backgroundSize;
  void set backgroundSize(String v) {_st.backgroundSize = _s(v);}
  String get blendMode => _st.blendMode;
  void set blendMode(String v) {_st.blendMode = _s(v);}
  String get border => _st.border;
  void set border(String v) {_st.border = _s(v);}
  String get borderAfter => _st.borderAfter;
  void set borderAfter(String v) {_st.borderAfter = _s(v);}
  String get borderAfterColor => _st.borderAfterColor;
  void set borderAfterColor(String v) {_st.borderAfterColor = _s(v);}
  String get borderAfterStyle => _st.borderAfterStyle;
  void set borderAfterStyle(String v) {_st.borderAfterStyle = _s(v);}
  String get borderAfterWidth => _st.borderAfterWidth;
  void set borderAfterWidth(String v) {_st.borderAfterWidth = _s(v);}
  String get borderBefore => _st.borderBefore;
  void set borderBefore(String v) {_st.borderBefore = _s(v);}
  String get borderBeforeColor => _st.borderBeforeColor;
  void set borderBeforeColor(String v) {_st.borderBeforeColor = _s(v);}
  String get borderBeforeStyle => _st.borderBeforeStyle;
  void set borderBeforeStyle(String v) {_st.borderBeforeStyle = _s(v);}
  String get borderBeforeWidth => _st.borderBeforeWidth;
  void set borderBeforeWidth(String v) {_st.borderBeforeWidth = _s(v);}
  String get borderBottom => _st.borderBottom;
  void set borderBottom(String v) {_st.borderBottom = _s(v);}
  String get borderBottomColor => _st.borderBottomColor;
  void set borderBottomColor(String v) {_st.borderBottomColor = _s(v);}
  String get borderBottomLeftRadius => _st.borderBottomLeftRadius;
  void set borderBottomLeftRadius(String v) {_st.borderBottomLeftRadius = _s(v);}
  String get borderBottomRightRadius => _st.borderBottomRightRadius;
  void set borderBottomRightRadius(String v) {_st.borderBottomRightRadius = _s(v);}
  String get borderBottomStyle => _st.borderBottomStyle;
  void set borderBottomStyle(String v) {_st.borderBottomStyle = _s(v);}
  String get borderBottomWidth => _st.borderBottomWidth;
  void set borderBottomWidth(String v) {_st.borderBottomWidth = _s(v);}
  String get borderCollapse => _st.borderCollapse;
  void set borderCollapse(String v) {_st.borderCollapse = _s(v);}
  String get borderColor => _st.borderColor;
  void set borderColor(String v) {_st.borderColor = _s(v);}
  String get borderEnd => _st.borderEnd;
  void set borderEnd(String v) {_st.borderEnd = _s(v);}
  String get borderEndColor => _st.borderEndColor;
  void set borderEndColor(String v) {_st.borderEndColor = _s(v);}
  String get borderEndStyle => _st.borderEndStyle;
  void set borderEndStyle(String v) {_st.borderEndStyle = _s(v);}
  String get borderEndWidth => _st.borderEndWidth;
  void set borderEndWidth(String v) {_st.borderEndWidth = _s(v);}
  String get borderFit => _st.borderFit;
  void set borderFit(String v) {_st.borderFit = _s(v);}
  String get borderHorizontalSpacing => _st.borderHorizontalSpacing;
  void set borderHorizontalSpacing(String v) {_st.borderHorizontalSpacing = _s(v);}
  String get borderImage => _st.borderImage;
  void set borderImage(String v) {_st.borderImage = _s(v);}
  String get borderImageOutset => _st.borderImageOutset;
  void set borderImageOutset(String v) {_st.borderImageOutset = _s(v);}
  String get borderImageRepeat => _st.borderImageRepeat;
  void set borderImageRepeat(String v) {_st.borderImageRepeat = _s(v);}
  String get borderImageSlice => _st.borderImageSlice;
  void set borderImageSlice(String v) {_st.borderImageSlice = _s(v);}
  String get borderImageSource => _st.borderImageSource;
  void set borderImageSource(String v) {_st.borderImageSource = _s(v);}
  String get borderImageWidth => _st.borderImageWidth;
  void set borderImageWidth(String v) {_st.borderImageWidth = _s(v);}
  String get borderLeft => _st.borderLeft;
  void set borderLeft(String v) {_st.borderLeft = _s(v);}
  String get borderLeftColor => _st.borderLeftColor;
  void set borderLeftColor(String v) {_st.borderLeftColor = _s(v);}
  String get borderLeftStyle => _st.borderLeftStyle;
  void set borderLeftStyle(String v) {_st.borderLeftStyle = _s(v);}
  String get borderLeftWidth => _st.borderLeftWidth;
  void set borderLeftWidth(String v) {_st.borderLeftWidth = _s(v);}
  String get borderRadius => _st.borderRadius;
  void set borderRadius(String v) {_st.borderRadius = _s(v);}
  String get borderRight => _st.borderRight;
  void set borderRight(String v) {_st.borderRight = _s(v);}
  String get borderRightColor => _st.borderRightColor;
  void set borderRightColor(String v) {_st.borderRightColor = _s(v);}
  String get borderRightStyle => _st.borderRightStyle;
  void set borderRightStyle(String v) {_st.borderRightStyle = _s(v);}
  String get borderRightWidth => _st.borderRightWidth;
  void set borderRightWidth(String v) {_st.borderRightWidth = _s(v);}
  String get borderSpacing => _st.borderSpacing;
  void set borderSpacing(String v) {_st.borderSpacing = _s(v);}
  String get borderStart => _st.borderStart;
  void set borderStart(String v) {_st.borderStart = _s(v);}
  String get borderStartColor => _st.borderStartColor;
  void set borderStartColor(String v) {_st.borderStartColor = _s(v);}
  String get borderStartStyle => _st.borderStartStyle;
  void set borderStartStyle(String v) {_st.borderStartStyle = _s(v);}
  String get borderStartWidth => _st.borderStartWidth;
  void set borderStartWidth(String v) {_st.borderStartWidth = _s(v);}
  String get borderStyle => _st.borderStyle;
  void set borderStyle(String v) {_st.borderStyle = _s(v);}
  String get borderTop => _st.borderTop;
  void set borderTop(String v) {_st.borderTop = _s(v);}
  String get borderTopColor => _st.borderTopColor;
  void set borderTopColor(String v) {_st.borderTopColor = _s(v);}
  String get borderTopLeftRadius => _st.borderTopLeftRadius;
  void set borderTopLeftRadius(String v) {_st.borderTopLeftRadius = _s(v);}
  String get borderTopRightRadius => _st.borderTopRightRadius;
  void set borderTopRightRadius(String v) {_st.borderTopRightRadius = _s(v);}
  String get borderTopStyle => _st.borderTopStyle;
  void set borderTopStyle(String v) {_st.borderTopStyle = _s(v);}
  String get borderTopWidth => _st.borderTopWidth;
  void set borderTopWidth(String v) {_st.borderTopWidth = _s(v);}
  String get borderVerticalSpacing => _st.borderVerticalSpacing;
  void set borderVerticalSpacing(String v) {_st.borderVerticalSpacing = _s(v);}
  String get borderWidth => _st.borderWidth;
  void set borderWidth(String v) {_st.borderWidth = _s(v);}
  String get bottom => _st.bottom;
  void set bottom(String v) {_st.bottom = _s(v);}
  String get boxAlign => _st.boxAlign;
  void set boxAlign(String v) {_st.boxAlign = _s(v);}
  String get boxDecorationBreak => _st.boxDecorationBreak;
  void set boxDecorationBreak(String v) {_st.boxDecorationBreak = _s(v);}
  String get boxDirection => _st.boxDirection;
  void set boxDirection(String v) {_st.boxDirection = _s(v);}
  String get boxFlex => _st.boxFlex;
  void set boxFlex(String v) {_st.boxFlex = _s(v);}
  String get boxFlexGroup => _st.boxFlexGroup;
  void set boxFlexGroup(String v) {_st.boxFlexGroup = _s(v);}
  String get boxLines => _st.boxLines;
  void set boxLines(String v) {_st.boxLines = _s(v);}
  String get boxOrdinalGroup => _st.boxOrdinalGroup;
  void set boxOrdinalGroup(String v) {_st.boxOrdinalGroup = _s(v);}
  String get boxOrient => _st.boxOrient;
  void set boxOrient(String v) {_st.boxOrient = _s(v);}
  String get boxPack => _st.boxPack;
  void set boxPack(String v) {_st.boxPack = _s(v);}
  String get boxReflect => _st.boxReflect;
  void set boxReflect(String v) {_st.boxReflect = _s(v);}
  String get boxShadow => _st.boxShadow;
  void set boxShadow(String v) {_st.boxShadow = _s(v);}
  String get boxSizing => _st.boxSizing;
  void set boxSizing(String v) {_st.boxSizing = _s(v);}
  String get captionSide => _st.captionSide;
  void set captionSide(String v) {_st.captionSide = _s(v);}
  String get clear => _st.clear;
  void set clear(String v) {_st.clear = _s(v);}
  String get clip => _st.clip;
  void set clip(String v) {_st.clip = _s(v);}
  String get clipPath => _st.clipPath;
  void set clipPath(String v) {_st.clipPath = _s(v);}
  String get color => _st.color;
  void set color(String v) {_st.color = _s(v);}
  String get colorCorrection => _st.colorCorrection;
  void set colorCorrection(String v) {_st.colorCorrection = _s(v);}
  String get columnAxis => _st.columnAxis;
  void set columnAxis(String v) {_st.columnAxis = _s(v);}
  String get columnBreakAfter => _st.columnBreakAfter;
  void set columnBreakAfter(String v) {_st.columnBreakAfter = _s(v);}
  String get columnBreakBefore => _st.columnBreakBefore;
  void set columnBreakBefore(String v) {_st.columnBreakBefore = _s(v);}
  String get columnBreakInside => _st.columnBreakInside;
  void set columnBreakInside(String v) {_st.columnBreakInside = _s(v);}
  String get columnCount => _st.columnCount;
  void set columnCount(String v) {_st.columnCount = _s(v);}
  String get columnGap => _st.columnGap;
  void set columnGap(String v) {_st.columnGap = _s(v);}
  String get columnProgression => _st.columnProgression;
  void set columnProgression(String v) {_st.columnProgression = _s(v);}
  String get columnRule => _st.columnRule;
  void set columnRule(String v) {_st.columnRule = _s(v);}
  String get columnRuleColor => _st.columnRuleColor;
  void set columnRuleColor(String v) {_st.columnRuleColor = _s(v);}
  String get columnRuleStyle => _st.columnRuleStyle;
  void set columnRuleStyle(String v) {_st.columnRuleStyle = _s(v);}
  String get columnRuleWidth => _st.columnRuleWidth;
  void set columnRuleWidth(String v) {_st.columnRuleWidth = _s(v);}
  String get columnSpan => _st.columnSpan;
  void set columnSpan(String v) {_st.columnSpan = _s(v);}
  String get columnWidth => _st.columnWidth;
  void set columnWidth(String v) {_st.columnWidth = _s(v);}
  String get columns => _st.columns;
  void set columns(String v) {_st.columns = _s(v);}
  String get content => _st.content;
  void set content(String v) {_st.content = _s(v);}
  String get counterIncrement => _st.counterIncrement;
  void set counterIncrement(String v) {_st.counterIncrement = _s(v);}
  String get counterReset => _st.counterReset;
  void set counterReset(String v) {_st.counterReset = _s(v);}
  String get cursor => _st.cursor;
  void set cursor(String v) {_st.cursor = _s(v);}
  String get dashboardRegion => _st.dashboardRegion;
  void set dashboardRegion(String v) {_st.dashboardRegion = _s(v);}
  String get direction => _st.direction;
  void set direction(String v) {_st.direction = _s(v);}
  String get display => _st.display;
  void set display(String v) {_st.display = _s(v);}
  String get emptyCells => _st.emptyCells;
  void set emptyCells(String v) {_st.emptyCells = _s(v);}
  String get filter => _st.filter;
  void set filter(String v) {_st.filter = _s(v);}
  String get flex => _st.flex;
  void set flex(String v) {_st.flex = _s(v);}
  String get flexBasis => _st.flexBasis;
  void set flexBasis(String v) {_st.flexBasis = _s(v);}
  String get flexDirection => _st.flexDirection;
  void set flexDirection(String v) {_st.flexDirection = _s(v);}
  String get flexFlow => _st.flexFlow;
  void set flexFlow(String v) {_st.flexFlow = _s(v);}
  String get flexGrow => _st.flexGrow;
  void set flexGrow(String v) {_st.flexGrow = _s(v);}
  String get flexShrink => _st.flexShrink;
  void set flexShrink(String v) {_st.flexShrink = _s(v);}
  String get flexWrap => _st.flexWrap;
  void set flexWrap(String v) {_st.flexWrap = _s(v);}
  String get float => _st.float;
  void set float(String v) {_st.float = _s(v);}
  String get flowFrom => _st.flowFrom;
  void set flowFrom(String v) {_st.flowFrom = _s(v);}
  String get flowInto => _st.flowInto;
  void set flowInto(String v) {_st.flowInto = _s(v);}
  String get font => _st.font;
  void set font(String v) {_st.font = _s(v);}
  String get fontFamily => _st.fontFamily;
  void set fontFamily(String v) {_st.fontFamily = _s(v);}
  String get fontFeatureSettings => _st.fontFeatureSettings;
  void set fontFeatureSettings(String v) {_st.fontFeatureSettings = _s(v);}
  String get fontKerning => _st.fontKerning;
  void set fontKerning(String v) {_st.fontKerning = _s(v);}
  String get fontSize => _st.fontSize;
  void set fontSize(String v) {_st.fontSize = _s(v);}
  String get fontSizeDelta => _st.fontSizeDelta;
  void set fontSizeDelta(String v) {_st.fontSizeDelta = _s(v);}
  String get fontSmoothing => _st.fontSmoothing;
  void set fontSmoothing(String v) {_st.fontSmoothing = _s(v);}
  String get fontStretch => _st.fontStretch;
  void set fontStretch(String v) {_st.fontStretch = _s(v);}
  String get fontStyle => _st.fontStyle;
  void set fontStyle(String v) {_st.fontStyle = _s(v);}
  String get fontVariant => _st.fontVariant;
  void set fontVariant(String v) {_st.fontVariant = _s(v);}
  String get fontVariantLigatures => _st.fontVariantLigatures;
  void set fontVariantLigatures(String v) {_st.fontVariantLigatures = _s(v);}
  String get fontWeight => _st.fontWeight;
  void set fontWeight(String v) {_st.fontWeight = _s(v);}
  String get gridColumn => _st.gridColumn;
  void set gridColumn(String v) {_st.gridColumn = _s(v);}
  String get gridColumns => _st.gridColumns;
  void set gridColumns(String v) {_st.gridColumns = _s(v);}
  String get gridRow => _st.gridRow;
  void set gridRow(String v) {_st.gridRow = _s(v);}
  String get gridRows => _st.gridRows;
  void set gridRows(String v) {_st.gridRows = _s(v);}
  String get highlight => _st.highlight;
  void set highlight(String v) {_st.highlight = _s(v);}
  String get hyphenateCharacter => _st.hyphenateCharacter;
  void set hyphenateCharacter(String v) {_st.hyphenateCharacter = _s(v);}
  String get hyphenateLimitAfter => _st.hyphenateLimitAfter;
  void set hyphenateLimitAfter(String v) {_st.hyphenateLimitAfter = _s(v);}
  String get hyphenateLimitBefore => _st.hyphenateLimitBefore;
  void set hyphenateLimitBefore(String v) {_st.hyphenateLimitBefore = _s(v);}
  String get hyphenateLimitLines => _st.hyphenateLimitLines;
  void set hyphenateLimitLines(String v) {_st.hyphenateLimitLines = _s(v);}
  String get hyphens => _st.hyphens;
  void set hyphens(String v) {_st.hyphens = _s(v);}
  String get imageOrientation => _st.imageOrientation;
  void set imageOrientation(String v) {_st.imageOrientation = _s(v);}
  String get imageRendering => _st.imageRendering;
  void set imageRendering(String v) {_st.imageRendering = _s(v);}
  String get imageResolution => _st.imageResolution;
  void set imageResolution(String v) {_st.imageResolution = _s(v);}
  String get justifyContent => _st.justifyContent;
  void set justifyContent(String v) {_st.justifyContent = _s(v);}
  String get letterSpacing => _st.letterSpacing;
  void set letterSpacing(String v) {_st.letterSpacing = _s(v);}
  String get lineAlign => _st.lineAlign;
  void set lineAlign(String v) {_st.lineAlign = _s(v);}
  String get lineBoxContain => _st.lineBoxContain;
  void set lineBoxContain(String v) {_st.lineBoxContain = _s(v);}
  String get lineBreak => _st.lineBreak;
  void set lineBreak(String v) {_st.lineBreak = _s(v);}
  String get lineClamp => _st.lineClamp;
  void set lineClamp(String v) {_st.lineClamp = _s(v);}
  String get lineGrid => _st.lineGrid;
  void set lineGrid(String v) {_st.lineGrid = _s(v);}
  String get lineHeight => _st.lineHeight;
  void set lineHeight(String v) {_st.lineHeight = _s(v);}
  String get lineSnap => _st.lineSnap;
  void set lineSnap(String v) {_st.lineSnap = _s(v);}
  String get listStyle => _st.listStyle;
  void set listStyle(String v) {_st.listStyle = _s(v);}
  String get listStyleImage => _st.listStyleImage;
  void set listStyleImage(String v) {_st.listStyleImage = _s(v);}
  String get listStylePosition => _st.listStylePosition;
  void set listStylePosition(String v) {_st.listStylePosition = _s(v);}
  String get listStyleType => _st.listStyleType;
  void set listStyleType(String v) {_st.listStyleType = _s(v);}
  String get locale => _st.locale;
  void set locale(String v) {_st.locale = _s(v);}
  String get logicalHeight => _st.logicalHeight;
  void set logicalHeight(String v) {_st.logicalHeight = _s(v);}
  String get logicalWidth => _st.logicalWidth;
  void set logicalWidth(String v) {_st.logicalWidth = _s(v);}
  String get margin => _st.margin;
  void set margin(String v) {_st.margin = _s(v);}
  String get marginAfter => _st.marginAfter;
  void set marginAfter(String v) {_st.marginAfter = _s(v);}
  String get marginAfterCollapse => _st.marginAfterCollapse;
  void set marginAfterCollapse(String v) {_st.marginAfterCollapse = _s(v);}
  String get marginBefore => _st.marginBefore;
  void set marginBefore(String v) {_st.marginBefore = _s(v);}
  String get marginBeforeCollapse => _st.marginBeforeCollapse;
  void set marginBeforeCollapse(String v) {_st.marginBeforeCollapse = _s(v);}
  String get marginBottom => _st.marginBottom;
  void set marginBottom(String v) {_st.marginBottom = _s(v);}
  String get marginBottomCollapse => _st.marginBottomCollapse;
  void set marginBottomCollapse(String v) {_st.marginBottomCollapse = _s(v);}
  String get marginCollapse => _st.marginCollapse;
  void set marginCollapse(String v) {_st.marginCollapse = _s(v);}
  String get marginEnd => _st.marginEnd;
  void set marginEnd(String v) {_st.marginEnd = _s(v);}
  String get marginLeft => _st.marginLeft;
  void set marginLeft(String v) {_st.marginLeft = _s(v);}
  String get marginRight => _st.marginRight;
  void set marginRight(String v) {_st.marginRight = _s(v);}
  String get marginStart => _st.marginStart;
  void set marginStart(String v) {_st.marginStart = _s(v);}
  String get marginTop => _st.marginTop;
  void set marginTop(String v) {_st.marginTop = _s(v);}
  String get marginTopCollapse => _st.marginTopCollapse;
  void set marginTopCollapse(String v) {_st.marginTopCollapse = _s(v);}
  String get marquee => _st.marquee;
  void set marquee(String v) {_st.marquee = _s(v);}
  String get marqueeDirection => _st.marqueeDirection;
  void set marqueeDirection(String v) {_st.marqueeDirection = _s(v);}
  String get marqueeIncrement => _st.marqueeIncrement;
  void set marqueeIncrement(String v) {_st.marqueeIncrement = _s(v);}
  String get marqueeRepetition => _st.marqueeRepetition;
  void set marqueeRepetition(String v) {_st.marqueeRepetition = _s(v);}
  String get marqueeSpeed => _st.marqueeSpeed;
  void set marqueeSpeed(String v) {_st.marqueeSpeed = _s(v);}
  String get marqueeStyle => _st.marqueeStyle;
  void set marqueeStyle(String v) {_st.marqueeStyle = _s(v);}
  String get mask => _st.mask;
  void set mask(String v) {_st.mask = _s(v);}
  String get maskAttachment => _st.maskAttachment;
  void set maskAttachment(String v) {_st.maskAttachment = _s(v);}
  String get maskBoxImage => _st.maskBoxImage;
  void set maskBoxImage(String v) {_st.maskBoxImage = _s(v);}
  String get maskBoxImageOutset => _st.maskBoxImageOutset;
  void set maskBoxImageOutset(String v) {_st.maskBoxImageOutset = _s(v);}
  String get maskBoxImageRepeat => _st.maskBoxImageRepeat;
  void set maskBoxImageRepeat(String v) {_st.maskBoxImageRepeat = _s(v);}
  String get maskBoxImageSlice => _st.maskBoxImageSlice;
  void set maskBoxImageSlice(String v) {_st.maskBoxImageSlice = _s(v);}
  String get maskBoxImageSource => _st.maskBoxImageSource;
  void set maskBoxImageSource(String v) {_st.maskBoxImageSource = _s(v);}
  String get maskBoxImageWidth => _st.maskBoxImageWidth;
  void set maskBoxImageWidth(String v) {_st.maskBoxImageWidth = _s(v);}
  String get maskClip => _st.maskClip;
  void set maskClip(String v) {_st.maskClip = _s(v);}
  String get maskComposite => _st.maskComposite;
  void set maskComposite(String v) {_st.maskComposite = _s(v);}
  String get maskImage => _st.maskImage;
  void set maskImage(String v) {_st.maskImage = _s(v);}
  String get maskOrigin => _st.maskOrigin;
  void set maskOrigin(String v) {_st.maskOrigin = _s(v);}
  String get maskPosition => _st.maskPosition;
  void set maskPosition(String v) {_st.maskPosition = _s(v);}
  String get maskPositionX => _st.maskPositionX;
  void set maskPositionX(String v) {_st.maskPositionX = _s(v);}
  String get maskPositionY => _st.maskPositionY;
  void set maskPositionY(String v) {_st.maskPositionY = _s(v);}
  String get maskRepeat => _st.maskRepeat;
  void set maskRepeat(String v) {_st.maskRepeat = _s(v);}
  String get maskRepeatX => _st.maskRepeatX;
  void set maskRepeatX(String v) {_st.maskRepeatX = _s(v);}
  String get maskRepeatY => _st.maskRepeatY;
  void set maskRepeatY(String v) {_st.maskRepeatY = _s(v);}
  String get maskSize => _st.maskSize;
  void set maskSize(String v) {_st.maskSize = _s(v);}
  String get maxHeight => _st.maxHeight;
  void set maxHeight(String v) {_st.maxHeight = _s(v);}
  String get maxLogicalHeight => _st.maxLogicalHeight;
  void set maxLogicalHeight(String v) {_st.maxLogicalHeight = _s(v);}
  String get maxLogicalWidth => _st.maxLogicalWidth;
  void set maxLogicalWidth(String v) {_st.maxLogicalWidth = _s(v);}
  String get maxWidth => _st.maxWidth;
  void set maxWidth(String v) {_st.maxWidth = _s(v);}
  String get maxZoom => _st.maxZoom;
  void set maxZoom(String v) {_st.maxZoom = _s(v);}
  String get minHeight => _st.minHeight;
  void set minHeight(String v) {_st.minHeight = _s(v);}
  String get minLogicalHeight => _st.minLogicalHeight;
  void set minLogicalHeight(String v) {_st.minLogicalHeight = _s(v);}
  String get minLogicalWidth => _st.minLogicalWidth;
  void set minLogicalWidth(String v) {_st.minLogicalWidth = _s(v);}
  String get minWidth => _st.minWidth;
  void set minWidth(String v) {_st.minWidth = _s(v);}
  String get minZoom => _st.minZoom;
  void set minZoom(String v) {_st.minZoom = _s(v);}
  String get nbspMode => _st.nbspMode;
  void set nbspMode(String v) {_st.nbspMode = _s(v);}
  String get opacity => _st.opacity;
  void set opacity(String v) {_st.opacity = _s(v);}
  String get order => _st.order;
  void set order(String v) {_st.order = _s(v);}
  String get orientation => _st.orientation;
  void set orientation(String v) {_st.orientation = _s(v);}
  String get orphans => _st.orphans;
  void set orphans(String v) {_st.orphans = _s(v);}
  String get outline => _st.outline;
  void set outline(String v) {_st.outline = _s(v);}
  String get outlineColor => _st.outlineColor;
  void set outlineColor(String v) {_st.outlineColor = _s(v);}
  String get outlineOffset => _st.outlineOffset;
  void set outlineOffset(String v) {_st.outlineOffset = _s(v);}
  String get outlineStyle => _st.outlineStyle;
  void set outlineStyle(String v) {_st.outlineStyle = _s(v);}
  String get outlineWidth => _st.outlineWidth;
  void set outlineWidth(String v) {_st.outlineWidth = _s(v);}
  String get overflow => _st.overflow;
  void set overflow(String v) {_st.overflow = _s(v);}
  String get overflowScrolling => _st.overflowScrolling;
  void set overflowScrolling(String v) {_st.overflowScrolling = _s(v);}
  String get overflowWrap => _st.overflowWrap;
  void set overflowWrap(String v) {_st.overflowWrap = _s(v);}
  String get overflowX => _st.overflowX;
  void set overflowX(String v) {_st.overflowX = _s(v);}
  String get overflowY => _st.overflowY;
  void set overflowY(String v) {_st.overflowY = _s(v);}
  String get padding => _st.padding;
  void set padding(String v) {_st.padding = _s(v);}
  String get paddingAfter => _st.paddingAfter;
  void set paddingAfter(String v) {_st.paddingAfter = _s(v);}
  String get paddingBefore => _st.paddingBefore;
  void set paddingBefore(String v) {_st.paddingBefore = _s(v);}
  String get paddingBottom => _st.paddingBottom;
  void set paddingBottom(String v) {_st.paddingBottom = _s(v);}
  String get paddingEnd => _st.paddingEnd;
  void set paddingEnd(String v) {_st.paddingEnd = _s(v);}
  String get paddingLeft => _st.paddingLeft;
  void set paddingLeft(String v) {_st.paddingLeft = _s(v);}
  String get paddingRight => _st.paddingRight;
  void set paddingRight(String v) {_st.paddingRight = _s(v);}
  String get paddingStart => _st.paddingStart;
  void set paddingStart(String v) {_st.paddingStart = _s(v);}
  String get paddingTop => _st.paddingTop;
  void set paddingTop(String v) {_st.paddingTop = _s(v);}
  String get page => _st.page;
  void set page(String v) {_st.page = _s(v);}
  String get pageBreakAfter => _st.pageBreakAfter;
  void set pageBreakAfter(String v) {_st.pageBreakAfter = _s(v);}
  String get pageBreakBefore => _st.pageBreakBefore;
  void set pageBreakBefore(String v) {_st.pageBreakBefore = _s(v);}
  String get pageBreakInside => _st.pageBreakInside;
  void set pageBreakInside(String v) {_st.pageBreakInside = _s(v);}
  String get perspective => _st.perspective;
  void set perspective(String v) {_st.perspective = _s(v);}
  String get perspectiveOrigin => _st.perspectiveOrigin;
  void set perspectiveOrigin(String v) {_st.perspectiveOrigin = _s(v);}
  String get perspectiveOriginX => _st.perspectiveOriginX;
  void set perspectiveOriginX(String v) {_st.perspectiveOriginX = _s(v);}
  String get perspectiveOriginY => _st.perspectiveOriginY;
  void set perspectiveOriginY(String v) {_st.perspectiveOriginY = _s(v);}
  String get pointerEvents => _st.pointerEvents;
  void set pointerEvents(String v) {_st.pointerEvents = _s(v);}
  String get position => _st.position;
  void set position(String v) {_st.position = _s(v);}
  String get printColorAdjust => _st.printColorAdjust;
  void set printColorAdjust(String v) {_st.printColorAdjust = _s(v);}
  String get quotes => _st.quotes;
  void set quotes(String v) {_st.quotes = _s(v);}
  String get regionBreakAfter => _st.regionBreakAfter;
  void set regionBreakAfter(String v) {_st.regionBreakAfter = _s(v);}
  String get regionBreakBefore => _st.regionBreakBefore;
  void set regionBreakBefore(String v) {_st.regionBreakBefore = _s(v);}
  String get regionBreakInside => _st.regionBreakInside;
  void set regionBreakInside(String v) {_st.regionBreakInside = _s(v);}
  String get regionOverflow => _st.regionOverflow;
  void set regionOverflow(String v) {_st.regionOverflow = _s(v);}
  String get resize => _st.resize;
  void set resize(String v) {_st.resize = _s(v);}
  String get right => _st.right;
  void set right(String v) {_st.right = _s(v);}
  String get rtlOrdering => _st.rtlOrdering;
  void set rtlOrdering(String v) {_st.rtlOrdering = _s(v);}
  String get shapeInside => _st.shapeInside;
  void set shapeInside(String v) {_st.shapeInside = _s(v);}
  String get shapeMargin => _st.shapeMargin;
  void set shapeMargin(String v) {_st.shapeMargin = _s(v);}
  String get shapeOutside => _st.shapeOutside;
  void set shapeOutside(String v) {_st.shapeOutside = _s(v);}
  String get shapePadding => _st.shapePadding;
  void set shapePadding(String v) {_st.shapePadding = _s(v);}
  String get size => _st.size;
  void set size(String v) {_st.size = _s(v);}
  String get speak => _st.speak;
  void set speak(String v) {_st.speak = _s(v);}
  String get src => _st.src;
  void set src(String v) {_st.src = _s(v);}
  String get tableLayout => _st.tableLayout;
  void set tableLayout(String v) {_st.tableLayout = _s(v);}
  String get tabSize => _st.tabSize;
  void set tabSize(String v) {_st.tabSize = _s(v);}
  String get tapHighlightColor => _st.tapHighlightColor;
  void set tapHighlightColor(String v) {_st.tapHighlightColor = _s(v);}
  String get textAlign => _st.textAlign;
  void set textAlign(String v) {_st.textAlign = _s(v);}
  String get textAlignLast => _st.textAlignLast;
  void set textAlignLast(String v) {_st.textAlignLast = _s(v);}
  String get textCombine => _st.textCombine;
  void set textCombine(String v) {_st.textCombine = _s(v);}
  String get textDecoration => _st.textDecoration;
  void set textDecoration(String v) {_st.textDecoration = _s(v);}
  String get textDecorationLine => _st.textDecorationLine;
  void set textDecorationLine(String v) {_st.textDecorationLine = _s(v);}
  String get textDecorationsInEffect => _st.textDecorationsInEffect;
  void set textDecorationsInEffect(String v) {_st.textDecorationsInEffect = _s(v);}
  String get textDecorationStyle => _st.textDecorationStyle;
  void set textDecorationStyle(String v) {_st.textDecorationStyle = _s(v);}
  String get textEmphasis => _st.textEmphasis;
  void set textEmphasis(String v) {_st.textEmphasis = _s(v);}
  String get textEmphasisColor => _st.textEmphasisColor;
  void set textEmphasisColor(String v) {_st.textEmphasisColor = _s(v);}
  String get textEmphasisPosition => _st.textEmphasisPosition;
  void set textEmphasisPosition(String v) {_st.textEmphasisPosition = _s(v);}
  String get textEmphasisStyle => _st.textEmphasisStyle;
  void set textEmphasisStyle(String v) {_st.textEmphasisStyle = _s(v);}
  String get textFillColor => _st.textFillColor;
  void set textFillColor(String v) {_st.textFillColor = _s(v);}
  String get textIndent => _st.textIndent;
  void set textIndent(String v) {_st.textIndent = _s(v);}
  String get textLineThrough => _st.textLineThrough;
  void set textLineThrough(String v) {_st.textLineThrough = _s(v);}
  String get textLineThroughColor => _st.textLineThroughColor;
  void set textLineThroughColor(String v) {_st.textLineThroughColor = _s(v);}
  String get textLineThroughMode => _st.textLineThroughMode;
  void set textLineThroughMode(String v) {_st.textLineThroughMode = _s(v);}
  String get textLineThroughStyle => _st.textLineThroughStyle;
  void set textLineThroughStyle(String v) {_st.textLineThroughStyle = _s(v);}
  String get textLineThroughWidth => _st.textLineThroughWidth;
  void set textLineThroughWidth(String v) {_st.textLineThroughWidth = _s(v);}
  String get textOrientation => _st.textOrientation;
  void set textOrientation(String v) {_st.textOrientation = _s(v);}
  String get textOverflow => _st.textOverflow;
  void set textOverflow(String v) {_st.textOverflow = _s(v);}
  String get textOverline => _st.textOverline;
  void set textOverline(String v) {_st.textOverline = _s(v);}
  String get textOverlineColor => _st.textOverlineColor;
  void set textOverlineColor(String v) {_st.textOverlineColor = _s(v);}
  String get textOverlineMode => _st.textOverlineMode;
  void set textOverlineMode(String v) {_st.textOverlineMode = _s(v);}
  String get textOverlineStyle => _st.textOverlineStyle;
  void set textOverlineStyle(String v) {_st.textOverlineStyle = _s(v);}
  String get textOverlineWidth => _st.textOverlineWidth;
  void set textOverlineWidth(String v) {_st.textOverlineWidth = _s(v);}
  String get textRendering => _st.textRendering;
  void set textRendering(String v) {_st.textRendering = _s(v);}
  String get textSecurity => _st.textSecurity;
  void set textSecurity(String v) {_st.textSecurity = _s(v);}
  String get textShadow => _st.textShadow;
  void set textShadow(String v) {_st.textShadow = _s(v);}
  String get textSizeAdjust => _st.textSizeAdjust;
  void set textSizeAdjust(String v) {_st.textSizeAdjust = _s(v);}
  String get textStroke => _st.textStroke;
  void set textStroke(String v) {_st.textStroke = _s(v);}
  String get textStrokeColor => _st.textStrokeColor;
  void set textStrokeColor(String v) {_st.textStrokeColor = _s(v);}
  String get textStrokeWidth => _st.textStrokeWidth;
  void set textStrokeWidth(String v) {_st.textStrokeWidth = _s(v);}
  String get textTransform => _st.textTransform;
  void set textTransform(String v) {_st.textTransform = _s(v);}
  String get textUnderline => _st.textUnderline;
  void set textUnderline(String v) {_st.textUnderline = _s(v);}
  String get textUnderlineColor => _st.textUnderlineColor;
  void set textUnderlineColor(String v) {_st.textUnderlineColor = _s(v);}
  String get textUnderlineMode => _st.textUnderlineMode;
  void set textUnderlineMode(String v) {_st.textUnderlineMode = _s(v);}
  String get textUnderlineStyle => _st.textUnderlineStyle;
  void set textUnderlineStyle(String v) {_st.textUnderlineStyle = _s(v);}
  String get textUnderlineWidth => _st.textUnderlineWidth;
  void set textUnderlineWidth(String v) {_st.textUnderlineWidth = _s(v);}
  String get transform => _st.transform;
  void set transform(String v) {_st.transform = _s(v);}
  String get transformOrigin => _st.transformOrigin;
  void set transformOrigin(String v) {_st.transformOrigin = _s(v);}
  String get transformOriginX => _st.transformOriginX;
  void set transformOriginX(String v) {_st.transformOriginX = _s(v);}
  String get transformOriginY => _st.transformOriginY;
  void set transformOriginY(String v) {_st.transformOriginY = _s(v);}
  String get transformOriginZ => _st.transformOriginZ;
  void set transformOriginZ(String v) {_st.transformOriginZ = _s(v);}
  String get transformStyle => _st.transformStyle;
  void set transformStyle(String v) {_st.transformStyle = _s(v);}
  String get transition => _st.transition;
  void set transition(String v) {_st.transition = _s(v);}
  String get transitionDelay => _st.transitionDelay;
  void set transitionDelay(String v) {_st.transitionDelay = _s(v);}
  String get transitionDuration => _st.transitionDuration;
  void set transitionDuration(String v) {_st.transitionDuration = _s(v);}
  String get transitionProperty => _st.transitionProperty;
  void set transitionProperty(String v) {_st.transitionProperty = _s(v);}
  String get transitionTimingFunction => _st.transitionTimingFunction;
  void set transitionTimingFunction(String v) {_st.transitionTimingFunction = _s(v);}
  String get unicodeBidi => _st.unicodeBidi;
  void set unicodeBidi(String v) {_st.unicodeBidi = _s(v);}
  String get unicodeRange => _st.unicodeRange;
  void set unicodeRange(String v) {_st.unicodeRange = _s(v);}
  String get userDrag => _st.userDrag;
  void set userDrag(String v) {_st.userDrag = _s(v);}
  String get userModify => _st.userModify;
  void set userModify(String v) {_st.userModify = _s(v);}
  String get userSelect => _st.userSelect;
  void set userSelect(String v) {_st.userSelect = _s(v);}
  String get userZoom => _st.userZoom;
  void set userZoom(String v) {_st.userZoom = _s(v);}
  String get verticalAlign => _st.verticalAlign;
  void set verticalAlign(String v) {_st.verticalAlign = _s(v);}
  String get visibility => _st.visibility;
  void set visibility(String v) {_st.visibility = _s(v);}
  String get whiteSpace => _st.whiteSpace;
  void set whiteSpace(String v) {_st.whiteSpace = _s(v);}
  String get widows => _st.widows;
  void set widows(String v) {_st.widows = _s(v);}
  String get wordBreak => _st.wordBreak;
  void set wordBreak(String v) {_st.wordBreak = _s(v);}
  String get wordSpacing => _st.wordSpacing;
  void set wordSpacing(String v) {_st.wordSpacing = _s(v);}
  String get wordWrap => _st.wordWrap;
  void set wordWrap(String v) {_st.wordWrap = _s(v);}
  String get wrap => _st.wrap;
  void set wrap(String v) {_st.wrap = _s(v);}
  String get wrapFlow => _st.wrapFlow;
  void set wrapFlow(String v) {_st.wrapFlow = _s(v);}
  String get wrapThrough => _st.wrapThrough;
  void set wrapThrough(String v) {_st.wrapThrough = _s(v);}
  String get writingMode => _st.writingMode;
  void set writingMode(String v) {_st.writingMode = _s(v);}
  String get zIndex => _st.zIndex;
  void set zIndex(String v) {_st.zIndex = _s(v);}
  String get zoom => _st.zoom;
  void set zoom(String v) {_st.zoom = _s(v);}
}
