#!/bin/bash
# d2d
#
#	Purpose:
#		Generates API Reference for rikulo
#
#Copyright (C) 2012 Potix Corporation. All Rights Reserved.
#
nodosfilewarning=true
SDK=/usr/dart/dart-sdk
if [ ! -d $SDK ] ; then
  echo $SDK not found
  echo "Please link /usr/dart to Dart Editor's folder."
  exit
fi
homedir=$0
homedir=${homedir%/*}
if [ "$homedir" = "." ] ; then
  homedir=".."
elif [ "$homedir" = "${homedir%/*}" ] ; then
  homedir="."
else
  homedir=${homedir%/*}
fi
if [ "$TERM" = "cygwin" ] || [ "$OSTYPE" = "cygwin" ] ; then
  homedir=$(cygpath -u $homedir)
  dartdoc=dartdoc.bat
else
  dartdoc=dartdoc
fi
outdir=$homedir/out
libdir=$homedir/lib

mkdir -p $outdir
if [ -d $outdir/docs ] ; then
	rm -rf $outdir/docs
fi

PATH=$PATH:$SDK/bin
echo Compiling $libdir
$dartdoc --out $outdir/docs $libdir/*.dart $libdir/view/*.dart 
if [ ! -f $outdir/docs/index.html ] ; then
	echo $outdir/docs/index.html not found. Failed?
	exit 1
fi

cd $outdir/docs
echo Process HTML files at $(pwd)
tooldir=../../tool/lib

function doHTML {
	sedfl=$1
	if [ ! -f $sedfl ] ; then
		echo $sedfl not found
		exit
	fi
	for f in *; do
		if [ -d $f ] ; then
			(
			echo Process $f
			cd $f
			doHTML ../$sedfl
			)
		elif [ ${f%.html} != $f ] ; then
			sed -f $sedfl $f > dd.tmp
			mv -f dd.tmp $f
		fi
	done
}

if [ -f index.html ] ; then
	doHTML $tooldir/index.html.sed
else
	echo index.html not found in $(pwd)
fi
